workflows:
  android-apk:
    name: Build V2Ray APK
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Fix Gradle wrapper
        script: |
          chmod +x gradlew
          sed -i 's/DEFAULT_JVM_OPTS=.*/DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"/' gradlew

      - name: Check Gradle
        script: |
          ./gradlew --version

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - "app/build/outputs/apk/debug/*.apk"
