workflows:
  android-apk:
    name: Android APK
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      vars:
        PACKAGE_NAME: "com.example.v2ray"

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Make Gradle executable
        script: |
          chmod +x ./gradlew

      - name: Build APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - "**/build/outputs/apk/**/*.apk"
